name: VmtkMonai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - vmtk
  - vtk
  - pytorch=*=*cuda*
  - torchvision=*=*cuda*
  - monai
  - numpy
  - tqdm
  - einops
  - nibabel
  - pyvista
  - pandas
  - scikit-image